### ISSUE TITLE
Build OA on ROS2 Foxy

### ISSUE THREAD

**Issue by pductruong** [intel/ros2_object_analytics#120]
I'm trying to build OA on my ROS Foxy. When i build `object_analytics_node` i got this:
`/home/fsdf/ros2_ws/src/ros2_object_analytics/object_analytics_node/src/tracker/tracking_node.cpp: In constructor ‘object_analytics_node::tracker::TrackingNode::TrackingNode(rclcpp::NodeOptions)’:
/home/fsdf/ros2_ws/src/ros2_object_analytics/object_analytics_node/src/tracker/tracking_node.cpp:44:88: error: no matching function for call to ‘object_analytics_node::tracker::TrackingNode::create_subscription<sensor_msgs::msg::Image>(const char [], object_analytics_node::tracker::TrackingNode::TrackingNode(rclcpp::NodeOptions)::<lambda(sensor_msgs::msg::Image_<std::allocator<void> >::SharedPtr)>&)’
   44 | iption<sensor_msgs::msg::Image>(Const::kTopicRgb,rgb_callback);
`
Any help would be appreciated thank you.

**Comment by tadmorgan** [comment]
Was there a solution you can share @pductruong? I'm looking at using something like OA but need to use Foxy since I have a L515. Thanks!

**Comment by pductruong** [comment]
> Was there a solution you can share @pductruong? I'm looking at using something like OA but need to use Foxy since I have a L515. Thanks!

Currently, this project only support OpenVino Toolkit 2020.3. You must install OpenVINO in ubuntu 18.04. If you want use ROS Foxy, u can build Foxy from source on Ubuntu 18.04. It work for me
