### ISSUE TITLE
[ERROR] [movidius_ncs_stream]: Error: there is no device at the given index or name

### ISSUE THREAD

**Issue by RachelRen05** [intel/ros2_object_analytics#64]
$ ros2 launch object_analytics_node object_analytics.launch.py
[INFO] [launch]: process[realsense_ros2_camera-1]: started with pid [3612]
[INFO] [launch]: process[api_composition-2]: started with pid [3613]
[INFO] [launch]: process[api_composition_cli-3]: started with pid [3614]
[INFO] [launch]: process[object_analytics_node-4]: started with pid [3615]
[INFO] [launch]: process[marker_publisher-5]: started with pid [3616]
[INFO] [launch]: process[rviz2-6]: started with pid [3621]
[INFO] [object_analytics_node]: Load library /opt/ros/crystal/lib/libsplitter_component.so
[INFO] [object_analytics_node]: Instantiate class object_analytics_node::splitter::SplitterNode
[INFO] [object_analytics_node]: Load library /opt/ros/crystal/lib/libsegmenter_component.so
[INFO] [marker_publisher]: Start MarkerPublisher ...
[INFO] [RealSenseCameraNode]: RealSense ROS v2. 0.1
[INFO] [RealSenseCameraNode]: Running with LibRealSense v2.16.5
[INFO] [RealSenseCameraNode]: getParameters...
[INFO] [RealSenseCameraNode]: setupDevice...
[INFO] [RealSenseCameraNode]: Device Name: Intel RealSense D435
[INFO] [RealSenseCameraNode]: Device Serial No: 819312070273
[INFO] [RealSenseCameraNode]: Device FW version: 05.09.02.00
[INFO] [RealSenseCameraNode]: Device Product ID: 0B07
[INFO] [RealSenseCameraNode]: Sync Mode: On
[INFO] [RealSenseCameraNode]: Device Sensors: 
[INFO] [RealSenseCameraNode]: Stereo Module was found.
[INFO] [RealSenseCameraNode]: RGB Camera was found.
[INFO] [RealSenseCameraNode]: Fisheye sensor isn't supported by current device! -- Skipping...
[INFO] [RealSenseCameraNode]: Gyro sensor isn't supported by current device! -- Skipping...
[INFO] [RealSenseCameraNode]: Accel sensor isn't supported by current device! -- Skipping...
[INFO] [RealSenseCameraNode]: setupPublishers...
[INFO] [object_analytics_node]: Instantiate class object_analytics_node::segmenter::SegmenterNode
[INFO] [RealSenseCameraNode]: setupStreams...
[INFO] [RealSenseCameraNode]: depth stream is enabled - width: 640, height: 480, fps: 30
[INFO] [RealSenseCameraNode]: infra1 stream is enabled - width: 640, height: 480, fps: 30
[INFO] [RealSenseCameraNode]: infra2 stream is enabled - width: 640, height: 480, fps: 30
[INFO] [RealSenseCameraNode]: color stream is enabled - width: 640, height: 480, fps: 30
[INFO] [object_analytics_node]: Load library /opt/ros/crystal/lib/libmoving_component.so
[INFO] [object_analytics_node]: Instantiate class object_analytics_node::movement::MovementNode
[INFO] [MovementNode]: ...Creating Moving Objects buffer...
[INFO] [rviz2]: Stereo is NOT SUPPORTED
[INFO] [rviz2]: OpenGl version: 3 (GLSL 1.3)
[INFO] [rviz2]: Stereo is NOT SUPPORTED
[INFO] [rviz2]: Stereo is NOT SUPPORTED
[INFO] [rviz2]: Stereo is NOT SUPPORTED
[INFO] [api_composition_cli]: Service not available, waiting again...
[INFO] [api_composition_cli]: Service not available, waiting again...
[INFO] [RealSenseCameraNode]: publishStaticTransforms...
[INFO] [RealSenseCameraNode]: RealSense Node Is Up!
[INFO] [api_composition_cli]: Sending request...
[INFO] [api_composition_cli]: Waiting for response...
[INFO] [api_composition]: Load library /home/intel/ros2_ws/install/movidius_ncs_stream/lib/libmovidius_ncs_stream.so
[INFO] [api_composition]: Instantiate class movidius_ncs_stream::NCSComposition
[DEBUG] [movidius_ncs_lib]: NCSImpl get parameters
[INFO] [movidius_ncs_lib]: use device_index = 0
[INFO] [movidius_ncs_lib]: use log_level = 0
[INFO] [movidius_ncs_lib]: use graph_file_path = /opt/movidius/ncappzoo/caffe/SSD_MobileNet/graph
[INFO] [movidius_ncs_lib]: use category_file_path = /opt/movidius/ncappzoo/data/ilsvrc12/voc21.txt
[INFO] [movidius_ncs_lib]: use cnn_type_ = mobilenetssd
[INFO] [movidius_ncs_lib]: use network_dimension = 300
[INFO] [movidius_ncs_lib]: use channel1_mean = 127.5
[INFO] [movidius_ncs_lib]: use channel2_mean = 127.5
[INFO] [movidius_ncs_lib]: use channel3_mean = 127.5
[INFO] [movidius_ncs_lib]: use top_n = 1
[INFO] [movidius_ncs_lib]: use scale = 0.007843
[ERROR] [movidius_ncs_stream]: Error: there is no device at the given index or name
[INFO] [api_composition_cli]: Result of load_node: success = true
[INFO] [launch]: process[api_composition_cli-3]: process has finished cleanly
[INFO] [launch]: process[api_composition-2]: process has finished cleanly
^C[WARNING] [launch.LaunchService]: user interrupted with ctrl-c (SIGINT)
[INFO] [rclcpp]: signal_handler(signal_value=2)
[ERROR] [launch]: process[realsense_ros2_camera-1] process has died [pid 3612, exit code -6, cmd '/opt/ros/crystal/lib/realsense_ros2_camera/realsense_ros2_camera'].
[ERROR] [launch]: process[object_analytics_node-4] process has died [pid 3615, exit code -11, cmd '/opt/ros/crystal/lib/object_analytics_node/object_analytics_node --localization /object_analytics/detected_objects:=/movidius_ncs_stream/detected_objects /object_analytics/registered_points:=/camera/depth/color/points'].
[INFO] [launch]: process[marker_publisher-5]: process has finished cleanly
[INFO] [rclcpp]: signal_handler(signal_value=2)
[INFO] [rclcpp]: signal_handler(signal_value=2)
double free or corruption (fasttop)
[ERROR] [launch]: process[rviz2-6] process has died [pid 3621, exit code -11, cmd '/opt/ros/crystal/lib/rviz2/rviz2 --display-config /opt/ros/crystal/share/object_analytics_node/launch/rviz/default.rviz'].

**Comment by yechun1** [comment]
this issue may cased by librealense https://github.com/IntelRealSense/librealsense/issues/2924.
And workaround by the PR https://github.com/IntelRealSense/librealsense/pull/2970.
Next time when bloom release update, the new debian package will be available.

**Comment by EwingKang** [comment]
I've provide some new info on the ROS2 branch.
https://github.com/intel/ros2_intel_movidius_ncs/issues/48
However, I do found out that, if unplug both RealSense and Movidius and plug them back in after each failure, I can get a 3/5 successful launch rate for `ros2 launch object_analytics_node object_analytics.launch.py`

**Comment by yechun1** [comment]
@EwingKang Would you please paste part of demsg while plugin device but no device found? 
I also found realsense device will miss after plugin for a while in my local after upgrade ubuntu kernel.

Not sure if it related with uvc modules that not be installed, from librealsense readme the uvc modules should be installed from binary by `sudo apt-get install librealsense2-dkms` ref to https://github.com/IntelRealSense/librealsense/blob/master/doc/distribution_linux.md, or be installed from source by `./scripts/patch-realsense-ubuntu-lts.sh` ref to 
https://github.com/IntelRealSense/librealsense/blob/master/doc/installation.md

but I failed to install the kernel module with network connection issue, not sure if you could have a try one your side.

**Comment by yechun1** [comment]
This issue are most likely related with librealsense kernel module, I have also reported the issue here https://github.com/IntelRealSense/librealsense/issues/3243

**Comment by EwingKang** [comment]
@yechun1 Here's the log file of one failed operation. 
 I can reproduce the failure result by executing in the order of **Realsense -> composition -> ncs_stream_launch**.

My installation of `sudo apt-get install librealsense2-dkms` is successful and without issue
#### syslog
[syslog.txt](https://github.com/intel/ros2_object_analytics/files/2858698/syslog.txt)

#### dmesg 
```
[ 4451.851700] usb 2-2: USB disconnect, device number 6
[ 4452.064696] usb 1-2: new high-speed USB device number 7 using xhci_hcd
[ 4452.213479] usb 1-2: New USB device found, idVendor=03e7, idProduct=2150
[ 4452.213485] usb 1-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 4452.213489] usb 1-2: Product: Movidius MA2X5X
[ 4452.213493] usb 1-2: Manufacturer: Movidius Ltd.
[ 4452.213496] usb 1-2: SerialNumber: 03e72150
[ 4483.341102] usb 1-2: USB disconnect, device number 7
[ 4484.600476] usb 1-2: new high-speed USB device number 8 using xhci_hcd
[ 4484.749227] usb 1-2: New USB device found, idVendor=03e7, idProduct=2150
[ 4484.749233] usb 1-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 4484.749238] usb 1-2: Product: Movidius MA2X5X
[ 4484.749241] usb 1-2: Manufacturer: Movidius Ltd.
[ 4484.749245] usb 1-2: SerialNumber: 03e72150
[ 4488.152331] usb 2-3: new SuperSpeed USB device number 11 using xhci_hcd
[ 4488.173214] usb 2-3: New USB device found, idVendor=8086, idProduct=0b3a
[ 4488.173220] usb 2-3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 4488.173224] usb 2-3: Product: Intel(R) RealSense(TM) Depth Camera 435i
[ 4488.173228] usb 2-3: Manufacturer: Intel(R) RealSense(TM) Depth Camera 435i
[ 4488.173232] usb 2-3: SerialNumber: 845523050367
[ 4488.186224] media: Linux media interface: v0.10
[ 4488.189792] PKCS#7 signature not signed with a trusted key
[ 4488.189799] videodev: loading out-of-tree module taints kernel.
[ 4488.189867] videodev: module verification failed: signature and/or required key missing - tainting kernel
[ 4488.190420] PKCS#7 signature not signed with a trusted key
[ 4488.192865] Linux video capture interface: v2.00
[ 4488.201779] PKCS#7 signature not signed with a trusted key
[ 4488.201801] PKCS#7 signature not signed with a trusted key
[ 4488.202479] uvcvideo: Found UVC 1.50 device Intel(R) RealSense(TM) Depth Camera 435i (8086:0b3a)
[ 4488.204159] uvcvideo: Unable to create debugfs 2-11 directory.
[ 4488.204276] uvcvideo 2-3:1.0: Entity type for entity Intel(R) RealSense(TM) Depth Ca was not initialized!
[ 4488.204278] uvcvideo 2-3:1.0: Entity type for entity Processing 2 was not initialized!
[ 4488.204279] uvcvideo 2-3:1.0: Entity type for entity Intel(R) RealSense(TM) Depth Ca was not initialized!
[ 4488.204280] uvcvideo 2-3:1.0: Entity type for entity Camera 1 was not initialized!
[ 4488.204416] input: Intel(R) RealSense(TM) Depth Ca as /devices/pci0000:00/0000:00:14.0/usb2/2-3/2-3:1.0/input/input12
[ 4488.204630] uvcvideo: Found UVC 1.50 device Intel(R) RealSense(TM) Depth Camera 435i (8086:0b3a)
[ 4488.205441] uvcvideo: Unable to create debugfs 2-11 directory.
[ 4488.205509] uvcvideo 2-3:1.3: Entity type for entity Processing 7 was not initialized!
[ 4488.205510] uvcvideo 2-3:1.3: Entity type for entity Extension 8 was not initialized!
[ 4488.205511] uvcvideo 2-3:1.3: Entity type for entity Camera 6 was not initialized!
[ 4488.205601] usbcore: registered new interface driver uvcvideo
[ 4488.205602] USB Video Class driver (1.1.2.realsense-1.3.4)
[ 4488.220911] PKCS#7 signature not signed with a trusted key
[ 4488.221253] PKCS#7 signature not signed with a trusted key
[ 4488.392249] hid-sensor-hub 0003:8086:0B3A.0004: No report with id 0xffffffff found
[ 4497.913945] uvcvideo: Failed to query (GET_CUR) UVC control 1 on unit 3: -32 (exp. 1024).
[ 4497.964706] uvcvideo: Failed to query (GET_CUR) UVC control 1 on unit 3: -32 (exp. 1024).
[ 4498.015014] uvcvideo: Failed to query (GET_CUR) UVC control 1 on unit 3: -32 (exp. 1024).
[ 4498.067382] hid-sensor-hub 0003:8086:0B3A.0004: No report with id 0xffffffff found
[ 4498.093276] uvcvideo: Failed to query (GET_CUR) UVC control 1 on unit 3: -32 (exp. 1024).
[ 4498.165203] uvcvideo: Failed to query (GET_CUR) UVC control 1 on unit 3: -32 (exp. 1024).
[ 4498.881822] usb 1-2: USB disconnect, device number 8
[ 4501.956126] hid-sensor-hub 0003:8086:0B3A.0004: No report with id 0xffffffff found
[ 4501.956272] hid-sensor-hub 0003:8086:0B3A.0004: No report with id 0xffffffff found
```

**Comment by challen-zhou** [comment]
Thanks all for the feedback and triage!
I would like to close this issue since it's on librealsense and NCS module driver side. Please feel free to let me know if you have further concern.
