### ISSUE TITLE
Flashing tracking boxes except for the first tracking object.

### ISSUE THREAD

**Issue by EwingKang** [intel/ros2_object_analytics#73]
I'm working on branch [devel](https://github.com/intel/ros2_object_analytics/tree/devel), commit [dd980db84](https://github.com/intel/ros2_object_analytics/commit/dd980db84e145c347002ca2275309cbdc0c51fa9). And encounter this issue.

I've open a image viewer with `ros2 run image_tools showimage image:=/object_analytics/image_publisher` for a better view of tracking result. 
I've notice that in the image viewer, as well as the rviz2 built-in one, the tracking boxes flash rapidly except for the left-most object. Please check the screen recording:

https://youtu.be/7mMnrlcUMIU
In this video, at first, you can see that every bounding box is flashing except for the left-most "chair". 
At 00:20, I've purposely blocked that object, and now the tracking box is "lock" on me. And when I'm moving, the tracking box on me is still stable even I'm not the left-most object. The left-most chair is flashing now.
At 00:45 I jump out of the frame, and the moment my bounding box disappeared (00:48), the left-most chair resume "locked" status while other boxes flashes. The behavior persisted even I moved back into the frame.
The video is much less "flashy" than on the monitor, probably due to screen recording frame rate.

I'm not sure is this a display bug or a tracking bug, but it appears to me that "persistence tracking" is only performing on the first "target object'. And that target object is selected from the left side of the frame (which is probably the order the object detection presents its detected list.)

**Comment by challenzhou** [comment]
Seems your video stream is not valid for us, could you have a check?
Roughly speaking, tracking doesn't favor any specific object, the splash may due to detection/tracking missing/glitching from frame to frame. But from your description, we would like to check if any improvement can be made from image_publisher side.

**Comment by EwingKang** [comment]
@challenzhou  Did you mean the YouTube video is not playable? Mmmm that's weird because I can view it from here, as well as my other collages, even without Youtube login (private view).

https://www.youtube.com/watch?v=7mMnrlcUMIU

**Comment by challenzhou** [comment]
This link works now, thanks!

**Comment by challen-zhou** [comment]
The issue has been solved by https://github.com/intel/ros2_object_analytics/pull/81.
