### ISSUE TITLE
Build failures with ROS 2 Dashing

### ISSUE THREAD

**Issue by nuclearsandwich** [intel/ros2_object_analytics#83]
The ROS 2 Dashing build is currently failing.
Here is a link to the official farm http://build.ros2.org/view/Dbin_uB64/job/Dbin_uB64__object_analytics_node__ubuntu_bionic_amd64__binary/3/console

The documentation here: https://index.ros.org/doc/ros2/Releases/Release-Dashing-Diademata/#changes-since-the-crystal-release includes a list of changes since Crystal which might prove useful in debugging.

**Comment by challen-zhou** [comment]
Thanks for the information!

Just checked the build error, the build machine missed liblz4 which is required from libpcl kdtree algorithm, you can install it by "sudo apt install liblz4-1" before build on ubuntu 18.04.
 
Also i updated the CMakeLists.txt to include liblz4 as prerequisite. The commit as "c674d9a0e7c2ea1eba1c9b4449790c92dc63ec2d", also re-tag 0.5.4_dashing, please feel free to let me know if any problem.

**Comment by challen-zhou** [comment]
@nuclearsandwich , may i know if this resolved your issue?

**Comment by nuclearsandwich** [comment]
Dependencies for the package need to be declared in the package.xml file as rosdep keys in order to appear in the build environment. https://github.com/intel/ros2_object_analytics/blob/master/object_analytics_node/package.xml

> also re-tag 0.5.4_dashing, please feel free to let me know if any problem.

Re-tagging isn't recommended as it can cause issues when multiple identical tags exist in our apt repository. For future changes I would suggest bumping the patch version.

**Comment by challen-zhou** [comment]
Done improve the package.xml, and taging it with 0.5.4, different tag with previous one, would you help have a try?

**Comment by challenzhou** [comment]
@nuclearsandwich , do you have any further question on this issue?

**Comment by nuclearsandwich** [comment]
> do you have any further question on this issue?


Nope. Thank you for resolving it!
