### ISSUE TITLE
when I launch I got an error

### ISSUE THREAD

**Issue by qingmingjie** [intel/ros2_object_analytics#9]
launch `ros2 pkg prefix object_analytics_launch`/share/object_analytics_launch/launch/analytics_movidius_ncs.py

ImportError: No module named 'launch.main'

**Comment by yechun1** [comment]
Please check the PYTHONPATH for launch package.

**Comment by yechun1** [comment]
this is not object_analytics issue. so I'll close it.

**Comment by DarshanLakkundi** [comment]
Hello @yechun1 , I want to use this package for object detection using Intel r200 IR sensors and simulate its accuracy in Gazebo. Can I use this for the same?

**Comment by yechun1** [comment]
@DarshanLakkundi glad to here you are interested in object analytics package, of course you could try to use it. If any issues, please feel free to let us known.

**Comment by DarshanLakkundi** [comment]
Thank you so much @yechun1 . The goal is to make a device for a person who is visually impaired. And honestly I am very new to ROS. Kindly help me for the same. And where can I find a Gazebo plugin with object detection code? Thanks, again.

**Comment by DarshanLakkundi** [comment]
@yechun1 Oh so there is no way to simulate object detection in Gazebo using Intel R200 plugins?? And when I say object detection I want the object to be detected for the person's mobility, I want the device to tell the person that there is a object within the specified distance, and later I might add layers of object recognition and so on..  and I am planning to use Intel R200, but the ros2_intel_movidius_ncs is for D400 series if I am not wrong??

**Comment by yechun1** [comment]
@DarshanLakkundi R200 is an old model that our modules NCS/OA have not supported, we only support D400+ series. About Gazebo plugin, here is a package [gazebo-realsense](https://github.com/intel/gazebo-realsense), but we have not verified object detection/tracking/localization in Gazebo simulation yet.

**Comment by DarshanLakkundi** [comment]
@yechun1 Okay. But I want to know is D400+ more powerful that R200? And I hoping that  I can get a D400+ Gazebo plugin??

**Comment by yechun1** [comment]
For more questions and discussions, would you please use answers.ros.org or https://discourse.ros.org, on that way, more people will join and share the experiences.
