### ISSUE TITLE
Does this work with NCS 2

### ISSUE THREAD

**Issue by farbod1277** [intel/ros2_object_analytics#91]
Given the movidius ncs is now discontinued, was wondering if this will also work with the new NCS 2. Thanks!

**Comment by challen-zhou** [comment]
> Given the movidius ncs is now discontinued, was wondering if this will also work with the new NCS 2. Thanks!

It should, you can have a try with openvino firstly, this module receives detection message from outside include openvino with NCS2.

**Comment by farbod1277** [comment]
> > Given the movidius ncs is now discontinued, was wondering if this will also work with the new NCS 2. Thanks!
> 
> It should, you can have a try with openvino firstly, this module receives detection message from outside include openvino with NCS2.

Thank you! Will try.
